---
- name: local variables play
  hosts: servers
  vars:
    tomcat_port: 8082
    jdk_version: 14
  tasks:
  - name: print local variables
    debug:
      msg: "tomcat port: {{tomcat_port}} and jdk version: {{jdk_version}}"  
...