---
- name: add user play
  hosts: all
  tasks:
  - name: create user
    user:
      name: joe
      password: welcome1
      create_home: yes
    become: yes
  - name: promote as sudoer
    lineinfile:
      path: /etc/sudoers
      insertafter: '^root.*'         
      line: 'joe ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -csf %s'
    become: yes  
...