Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/focal64"
    #config.vm.network "public_network"
    #config.vm.network "public_network", ip:"192.168.1.10"
    config.vm.network "public_network", bridge: ["Killer Wireless-n/a/ac 1535 Wireless Network Adapter"]
end