Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/focal64"
    #config.vm.network "private_network", type: "dhcp"
    #config.vm.network "private_network", ip: "192.168.10.11"
    config.vm.network "private_network", virtualbox_intnet: "network1", ip: "192.168.13.11"
end