Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/focal64"
    #config.vm.network "private_network", type: "dhcp"
    config.vm.network "private_network", virtualbox_intnet: "network2", ip: "192.168.10.10"
end